# Generated by Django 5.1.1 on 2024-12-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_movimiento_estado_nuevo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
