# Generated by Django 5.1.3 on 2024-12-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
